name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: dummy-bucket011
        AWS_ACCESS_KEY_ID: AKIA6ODU7KKUMPKPUCYBkey
        AWS_SECRET_ACCESS_KEY: PO/TzJQlK+j5VuDt/daF49jV+Qui1XFHS7wNFCOB
